apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-eks
automountServiceAccountToken: false
---
apiVersion: v1
kind: Secret
metadata:
  name: deploy-eks-secret
  annotations:
    kubernetes.io/service-account.name: deploy-eks
type: kubernetes.io/service-account-token
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deploy-eks-role
  namespace: default
rules: # ## Customize these to meet your requirements ##
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete","*"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete","*"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","watch","list","*"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["patch","*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: global-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: deploy-eks
  namespace: default
roleRef:
  kind: Role
  name: deploy-eks-role
  apiGroup: rbac.authorization.k8s.io